// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0vlzgpcvKC84XUk3o14XpBw_DtXIf7sg',
    appId: '1:828723503305:web:d0432df890d0d0ff8ced18',
    messagingSenderId: '828723503305',
    projectId: 'babyface-a1c8f',
    authDomain: 'babyface-a1c8f.firebaseapp.com',
    storageBucket: 'babyface-a1c8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0vlzgpcvKC84XUk3o14XpBw_DtXIf7sg',
    appId: '1:828723503305:android:d0432df890d0d0ff8ced18',
    messagingSenderId: '828723503305',
    projectId: 'babyface-a1c8f',
    storageBucket: 'babyface-a1c8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0vlzgpcvKC84XUk3o14XpBw_DtXIf7sg',
    appId: '1:828723503305:ios:d0432df890d0d0ff8ced18',
    messagingSenderId: '828723503305',
    projectId: 'babyface-a1c8f',
    storageBucket: 'babyface-a1c8f.firebasestorage.app',
    iosBundleId: 'com.anilkumar.futurebaby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0vlzgpcvKC84XUk3o14XpBw_DtXIf7sg',
    appId: '1:828723503305:ios:d0432df890d0d0ff8ced18',
    messagingSenderId: '828723503305',
    projectId: 'babyface-a1c8f',
    storageBucket: 'babyface-a1c8f.firebasestorage.app',
    iosBundleId: 'com.anilkumar.futurebaby',
  );
}
